export const images = {
  appBackground: require('./app-background.png'),
  logo: require('./logo.png'),
  loaderGif: require('./logo-animated.gif'),
  chevronRight: require('./chevron-right.png'),
  call: require('./call.png'),
  chatBubble: require('./chatbubble-ellipses-sharp.png'),
  taskList: require('./task-list-f.png'),
  videoCameraVintage: require('./video-camera-vintage-f.png'),
  star: require('./star.png'),
  tabOrder: require('./mdi_clock-arrow.png'),
  tabWallet: require('./famicons_wallet-outline.png'),
  tabNotification: require('./grommet-icons_mail-option.png'),
  tabProfile: require('./healthicons_ui-user-profile-outline.png'),
  tabHome: require('./material-symbols_home-outline-rounded.png'),
  leftArrow: require('./chevron.left.png'),
  cuidaNotificationBellOutline: require('./cuida_notification-bell-outline.png'),
  streamlineCustomerSupport: require('./streamline_customer-support-1.png'),
  uilLanguage: require('./uil_language.png'),
  streamlineCustomerSupportSolid: require('./streamline_customer-support-1-solid.png'),
  walletSharp: require('./wallet-sharp.png'),
  settings: require('./settings.png'),
  iconamoonProfileCircleFill: require('./iconamoon_profile-circle-fill.png'),
  timerOutline: require('./timer-outline.png'),
} as const;
