export const images = {
  appBackground: require('./app-background.png'),
  logo: require('./logo.png'),
  loaderGif: require('./logo-animated.gif'),
  chevronRight: require('./chevron-right.png'),
  makiArrow: require('./maki_arrow.png'),
  call: require('./call.png'),
  chatBubble: require('./chatbubble-ellipses-sharp.png'),
  taskList: require('./task-list-f.png'),
  videoCameraVintage: require('./video-camera-vintage-f.png'),
  star: require('./star.png'),
  tabOrder: require('./mdi_clock-arrow.png'),
  tabOrderActive: require('./mdi_clock-arrow-solid.png'),
  tabWallet: require('./famicons_wallet-outline.png'),
  tabWalletActive: require('./ion_wallet.png'),
  tabNotification: require('./grommet-icons_mail-option.png'),
  tabNotificationActive: require('./material-symbols-light_mail.png'),
  tabProfile: require('./healthicons_ui-user-profile-outline.png'),
  tabHome: require('./material-symbols_home-outline-rounded.png'),
  tabHomeActive: require('./material-symbols_home-rounded.png'),
  leftArrow: require('./chevron.left.png'),
  cuidaNotificationBellOutline: require('./cuida_notification-bell-outline.png'),
  streamlineCustomerSupport: require('./streamline_customer-support-1.png'),
  uilLanguage: require('./uil_language.png'),
  streamlineCustomerSupportSolid: require('./streamline_customer-support-1-solid.png'),
  walletSharp: require('./wallet-sharp.png'),
  settings: require('./settings.png'),
  iconamoonProfileCircleFill: require('./iconamoon_profile-circle-fill.png'),
  timerOutline: require('./timer-outline.png'),
  refreshIcon: require('./refreshIcon.png'),
  addIcon: require('./addIcon.png'),
  /** Low-opacity centre watermark for foreground incoming-chat overlay */
  incomingPushWatermark: require('./incoming-push-watermark.png'),
} as const;
